name: clients/ruby RSpec

on:
  push:
    paths:
      - "clients/ruby/**"
      - "servers/ruby/**"
      - ".github/workflows/clients-ruby-rspec.yml"
  pull_request:
    paths:
      - "clients/ruby/**"
      - "servers/ruby/**"
      - ".github/workflows/clients-ruby-rspec.yml"

jobs:
  rspec:
    uses: ./.github/workflows/_ruby-rspec.yml
    with:
      rspec-working-directory: clients/ruby
