name: clients/go RSpec

on:
  push:
    paths:
      - "clients/go/**"
      - "servers/ruby/**"
      - ".github/workflows/clients-go-rspec.yml"
  pull_request:
    paths:
      - "clients/go/**"
      - "servers/ruby/**"
      - ".github/workflows/clients-go-rspec.yml"

jobs:
  rspec:
    uses: ./.github/workflows/_ruby-rspec.yml
    with:
      rspec-working-directory: clients/go
      setup-go: true
