name: servers/ruby RSpec

on:
  push:
    paths:
      - "servers/ruby/**"
      - ".github/workflows/servers-ruby-rspec.yml"
  pull_request:
    paths:
      - "servers/ruby/**"
      - ".github/workflows/servers-ruby-rspec.yml"

jobs:
  rspec:
    uses: ./.github/workflows/_ruby-rspec.yml
    with:
      rspec-working-directory: servers/ruby
